### ISSUE TITLE
Documentation error, python call on windows

### ISSUE THREAD

**Issue by MathieuCGit** [jtackaberry/luadox#1]
Hello,

Just to mention calling python on windows is "python luadox -c luadox.conf" and not "python3 luadox -c luadox.conf"

![image](https://user-images.githubusercontent.com/83604945/126722281-4dc5740c-40c0-4a65-9145-522e348c80e6.png)

**Comment by jtackaberry** [comment]
Thanks for the correction, @MathieuCGit
