### ISSUE TITLE
UnicodeDecodeError on non-Unicode characters

### ISSUE THREAD

**Issue by DieterMerkenEDTB** [jtackaberry/luadox#4]
Hi,

First of all, I would like to say thanks for creating this tool. I'm working with a Lua framework on a daily basis and was positively surprised when checking the generated documentation files.

However, I noticed that for some string values, a Python UnicodeDecodeError is getting raised when the Lua source file is getting parsed.
![20220816_UnicodeDecodeError](https://user-images.githubusercontent.com/76052085/184897253-b52c8a7b-4ac8-4869-803c-745b72c08e99.png)

From performing some debugging, it became clear that the error occurs because there is some Greek string value present in the last file before the file mentioned by the command output (so in this case, the Greek string value was present in Kids.tws, not in Navigation.tws).

The issue got fixed by removing the following line of code from the Kids.tws file: `local test = "ΠΡΟΒΟΛΗ ΤΟΥ ΒΙΝΤΕΟ ΕΙΣΑΓΩΓΗΣ"`

Will non-Unicode characters also be supported in the future? Or some way to indicate that a specific piece of code should be ignored by LuaDox, perhaps something like a @ignore tag?

Kind regards,

Dieter

**Comment by jtackaberry** [comment]
Thanks for the bug report, Dieter.  I think this is a specific issue on Windows.  Can you try passing `--encoding utf8` to luadox and see if that helps?

**Comment by DieterMerkenEDTB** [comment]
Hi,

Thanks for the quick reply and suggestion, adding `--encoding utf8` when running LuaDox from the command prompt worked successfully as expected!

However, I would like to add that in the luadox.conf file, the following line was already present: `encoding = utf8` (as shown in the example configuration file), but the UnicodeDecodeError still occurred. Does the `--encoding utf8` argument in the command prompt serve a different purpose than the `encoding = utf8` line in the config file? Or could this be a Windows-specific behavior?

Thanks again!

Kind regards,

Dieter

**Comment by jtackaberry** [comment]
`encoding = utf8` in config is supposed to be equivalent to `--encoding utf8` on the command line that it isn't working this way is indeed a bug.

Separate from that, there's the question of whether LuaDox should default to utf8 on Windows, as opposed to the platform's preferred encoding (which is CP1252 on Windows).  I'm learning toward just forcing UTF8 on all platforms, but I don't have a strong intuition about which is the path of least resistance on Windows.

**Comment by DieterMerkenEDTB** [comment]
Hi,

Thanks for the additional explanation, that clears it up for me. Regardless of how you decide to handle it in the future, it's good to know that the workaround by passing it as an argument is successful for now. Worst case you could try to catch the error if on Windows and retry with utf8, but I also don't know if that will bring less resistance.

Anyway, thanks again for the quick support and solution.

Kind regards,

Dieter
